//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcilisBakiye
    {
        public int AcilisBakiyeID { get; set; }
        public Nullable<int> BinaID { get; set; }
        public Nullable<decimal> EkTutar { get; set; }
        public Nullable<decimal> AidatTutar { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
    }
}
