//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;

    public partial class AidatTanim
    {
        public int ID { get; set; }
        public int BinaID { get; set; }
        public int AidatYil { get; set; }
        public int AidatAy { get; set; }
        public decimal Tutar { get; set; }
    }
}
