//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AidatView
    {
        public string BinaAdi { get; set; }
        public int AidatID { get; set; }
        public string AidatAy { get; set; }
        public Nullable<int> AidatYil { get; set; }
        public Nullable<decimal> AidatTutar { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public string Durum { get; set; }
        public Nullable<int> BinaID { get; set; }
        public string AdSoyad { get; set; }
    }
}
