//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gider
    {
        public int GiderID { get; set; }
        public string GiderAciklama { get; set; }
        public Nullable<int> GiderTuruID { get; set; }
        public Nullable<decimal> GiderTutar { get; set; }
        public Nullable<System.DateTime> GiderTarih { get; set; }
        public Nullable<int> BinaID { get; set; }
        public string Durum { get; set; }
        public Nullable<int> GiderNo { get; set; }
    }
}
