//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HareketView
    {
        public int HareketID { get; set; }
        public int BinaID { get; set; }
        public string BinaAdi { get; set; }
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string AdSoyad { get; set; }
        public string OlayAciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Tur { get; set; }
    }
}
