//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kasa
    {
        public int KasaID { get; set; }
        public string KasaAy { get; set; }
        public Nullable<int> KasaYil { get; set; }
        public Nullable<decimal> KasaAidat { get; set; }
        public Nullable<decimal> KasaEk { get; set; }
        public Nullable<decimal> KasaToplam { get; set; }
        public Nullable<int> BinaID { get; set; }
        public Nullable<int> AyKodu { get; set; }
    }
}
