//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanicilarView
    {
        public string BinaAdi { get; set; }
        public int BinaID { get; set; }
        public string Adres { get; set; }
        public string VergiNo { get; set; }
        public Nullable<int> DaireSayisi { get; set; }
        public int KullaniciID { get; set; }
        public string KullaniciAdi { get; set; }
        public string AdSoyad { get; set; }
        public string Parola { get; set; }
        public string Telefon { get; set; }
        public string Yetki { get; set; }
        public string KullaniciDurumu { get; set; }
        public Nullable<System.DateTime> SozlesmeBitisTarihi { get; set; }
        public string BinaDurumu { get; set; }
        public string BinaKullaniciAdi { get; set; }
        public Nullable<System.DateTime> SozlesmeBaslamaTarihi { get; set; }
    }
}
