//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makbuz
    {
        public int MakbuzID { get; set; }
        public Nullable<int> MakbuzNo { get; set; }
        public Nullable<int> BinaID { get; set; }
        public Nullable<int> DaireID { get; set; }
        public Nullable<decimal> MabuzTutar { get; set; }
        public Nullable<System.DateTime> MakbuzTarihi { get; set; }
        public string Aciklama { get; set; }
        public string Durum { get; set; }
        public Nullable<bool> OnayliMi { get; set; }
    }
}
