//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakbuzSatir
    {
        public int MakbuzSatirID { get; set; }
        public Nullable<int> MakbuzID { get; set; }
        public string AyAdi { get; set; }
        public Nullable<int> YilAdi { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<int> DaireID { get; set; }
        public Nullable<int> BinaID { get; set; }
        public string Durum { get; set; }
        public string EkMiAidatMi { get; set; }
    }
}
