//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptVTEntities : DbContext
    {
        public AptVTEntities()
            : base("name=AptVTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aidat> Aidats { get; set; }
        public virtual DbSet<Daireler> Dairelers { get; set; }
        public virtual DbSet<Ek> Eks { get; set; }
        public virtual DbSet<Gider> Giders { get; set; }
        public virtual DbSet<GiderTuru> GiderTurus { get; set; }
        public virtual DbSet<Hareketler> Hareketlers { get; set; }
        public virtual DbSet<Kasa> Kasas { get; set; }
        public virtual DbSet<Makbuz> Makbuzs { get; set; }
        public virtual DbSet<Tahsilat> Tahsilats { get; set; }
        public virtual DbSet<AidatView> AidatViews { get; set; }
        public virtual DbSet<EkView> EkViews { get; set; }
        public virtual DbSet<GiderView> GiderViews { get; set; }
        public virtual DbSet<HareketView> HareketViews { get; set; }
        public virtual DbSet<KasaView> KasaViews { get; set; }
        public virtual DbSet<MakbuzView> MakbuzViews { get; set; }
        public virtual DbSet<TahsilatView> TahsilatViews { get; set; }
        public virtual DbSet<Binalar> Binalars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<KullanicilarView> KullanicilarViews { get; set; }
        public virtual DbSet<MakbuzSatir> MakbuzSatirs { get; set; }
        public virtual DbSet<MakbuzSatirView> MakbuzSatirViews { get; set; }
        public virtual DbSet<AcilisBakiye> AcilisBakiyes { get; set; }
        public virtual DbSet<Duyurular> Duyurulars { get; set; }
        public virtual DbSet<Notlar> Notlars { get; set; }
    }
}
