//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesinOdemelerView
    {
        public int DaireID { get; set; }
        public Nullable<int> DaireNo { get; set; }
        public string AdSoyad { get; set; }
        public int Yil { get; set; }
        public int BinaID { get; set; }
        public string Telefon { get; set; }
        public string YonetimdeMi { get; set; }
        public Nullable<decimal> Borc { get; set; }
        public string DaireDurum { get; set; }
        public string TC { get; set; }
        public int ID { get; set; }
    }
}
