//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApartmanAidatTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahsilatView
    {
        public int TahsilatID { get; set; }
        public string TahsilatAciklama { get; set; }
        public Nullable<decimal> TahsilatTutar { get; set; }
        public Nullable<System.DateTime> TahsilatTarih { get; set; }
        public Nullable<int> BinaID { get; set; }
        public string BinaAdi { get; set; }
        public string Durum { get; set; }
        public Nullable<int> TahsilatNo { get; set; }
        public Nullable<bool> DemirbasMi { get; set; }
    }
}
